#!/usr/bin/env python3
import argparse
import pathlib
import sys

import yaml
from scholarly import scholarly


def load_scholar_id(config_path: pathlib.Path) -> str:
    with config_path.open("r", encoding="utf-8") as handle:
        config = yaml.safe_load(handle)
    scholar_id = config.get("scholar_userid")
    if not scholar_id:
        raise ValueError("scholar_userid not found in _config.yml")
    return scholar_id


def fetch_bibtex_entries(scholar_id: str) -> list[str]:
    author = scholarly.search_author_id(scholar_id)
    author = scholarly.fill(author, sections=["publications"])

    entries: list[str] = []
    for publication in author.get("publications", []):
        try:
            filled = scholarly.fill(publication)
            entries.append(scholarly.bibtex(filled))
        except Exception as exc:
            print(f"Warning: failed to fetch publication: {exc}", file=sys.stderr)
    return entries


def write_bibtex(entries: list[str], output_path: pathlib.Path) -> None:
    header = "% Publications are synced automatically from Google Scholar.\n"
    header += "% This file was generated by scripts/update_publications.py.\n\n"
    output_path.write_text(header + "\n\n".join(entries) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Update publications from Google Scholar")
    parser.add_argument("--user-id", help="Google Scholar user ID")
    parser.add_argument(
        "--config",
        default="_config.yml",
        help="Path to site _config.yml (default: _config.yml)",
    )
    parser.add_argument(
        "--output",
        default="_bibliography/papers.bib",
        help="Output BibTeX file (default: _bibliography/papers.bib)",
    )
    args = parser.parse_args()

    config_path = pathlib.Path(args.config)
    output_path = pathlib.Path(args.output)

    scholar_id = args.user_id or load_scholar_id(config_path)
    entries = fetch_bibtex_entries(scholar_id)

    if not entries:
        print("No publications found. Output file not updated.", file=sys.stderr)
        return 1

    write_bibtex(entries, output_path)
    print(f"Wrote {len(entries)} entries to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
