#!/usr/bin/env python3
import argparse
import pathlib
import re
import sys

import yaml
from scholarly import scholarly


def load_scholar_id(config_path: pathlib.Path) -> str:
    with config_path.open("r", encoding="utf-8") as handle:
        config = yaml.safe_load(handle)
    scholar_id = config.get("scholar_userid")
    if not scholar_id:
        raise ValueError("scholar_userid not found in _config.yml")
    return scholar_id


def _bibtex_escape(value: str) -> str:
    """Escape the characters that have special meaning in a BibTeX value."""
    return (
        value.replace("\\", "\\textbackslash{}")
        .replace("{", "\\{")
        .replace("}", "\\}")
        .replace("&", r"\&")
        .replace("%", r"\%")
        .replace("#", r"\#")
        .replace("_", r"\_")
    )


def _entry_key(title: str, year: object, index: int) -> str:
    stem = re.sub(r"[^a-z0-9]+", "", title.lower())[:32] or "publication"
    year_stem = re.sub(r"[^a-z0-9]+", "", str(year).lower()) or "nd"
    return f"scholar{year_stem}{stem}{index}"


EXCLUDED_TITLES = {
    "sunshineasdisinfectantfoialawsandpubliccorruption",
    "asurveyofpublicorientedorganizationsanalyzingsocialmediadisinformation",
}


def _publication_to_bibtex(publication: dict, index: int) -> str:
    bib = publication.get("bib", {})
    title = str(bib.get("title", "Untitled publication"))
    # Jekyll Scholar expects every entry to have a numeric year when grouping
    # the bibliography. Google Scholar occasionally omits it for older records.
    year = bib.get("pub_year") or 0
    citation = str(bib.get("citation", ""))
    journal = bib.get("journal")
    if journal and str(journal).lower() == "pnas nexus":
        journal = "PNAS Nexus"
    if journal and str(journal).lower() == "journal of health economics":
        journal = "Journal of Health Economics"
    if journal and str(journal).lower() == "journal of public economics":
        journal = "Journal of Public Economics"
    authors = bib.get("author")
    fields = [("title", title)]
    if authors:
        fields.append(("author", str(authors)))
    if journal:
        fields.append(("journal", str(journal)))
    fields.append(("year", str(year)))
    if not journal and citation:
        fields.append(("note", citation))
    if publication.get("pub_url"):
        fields.append(("url", str(publication["pub_url"])))
    rendered = [f"@article{{{_entry_key(title, year, index)},"]
    rendered.extend(f"  {name}={{{_bibtex_escape(value)}}}" for name, value in fields)
    rendered.append("}")
    # Add commas between fields, but not after the final field.
    for position in range(1, len(rendered) - 1):
        if not rendered[position].endswith(","):
            rendered[position] += ","
    return "\n".join(rendered)


def fetch_bibtex_entries(scholar_id: str) -> list[str]:
    author = scholarly.search_author_id(scholar_id)
    author = scholarly.fill(author, sections=["publications"])

    entries: list[str] = []
    for publication in author.get("publications", []):
        title = str(publication.get("bib", {}).get("title", ""))
        normalized_title = re.sub(r"[^a-z0-9]+", "", title.lower())
        if normalized_title in EXCLUDED_TITLES:
            continue
        try:
            filled = scholarly.fill(publication)
            entries.append(_publication_to_bibtex(filled, len(entries) + 1))
        except Exception as exc:
            print(f"Warning: failed to fetch publication: {exc}", file=sys.stderr)
    return entries


def write_bibtex(entries: list[str], output_path: pathlib.Path) -> None:
    header = "% Publications are synced automatically from Google Scholar.\n"
    header += "% This file was generated by scripts/update_publications.py.\n\n"
    output_path.write_text(header + "\n\n".join(entries) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Update publications from Google Scholar")
    parser.add_argument("--user-id", help="Google Scholar user ID")
    parser.add_argument(
        "--config",
        default="_config.yml",
        help="Path to site _config.yml (default: _config.yml)",
    )
    parser.add_argument(
        "--output",
        default="_bibliography/papers.bib",
        help="Output BibTeX file (default: _bibliography/papers.bib)",
    )
    args = parser.parse_args()

    config_path = pathlib.Path(args.config)
    output_path = pathlib.Path(args.output)

    scholar_id = args.user_id or load_scholar_id(config_path)
    entries = fetch_bibtex_entries(scholar_id)

    if not entries:
        print("No publications found. Output file not updated.", file=sys.stderr)
        return 1

    write_bibtex(entries, output_path)
    print(f"Wrote {len(entries)} entries to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
